CREATE ROLE adm LOGIN
 PASSWORD 'bd2adm'
 SUPERUSER CREATEDB CREATEROLE;
 
CREATE ROLE usr LOGIN
 PASSWORD 'bd2user';
 
REVOKE ALL ON ALL TABLES IN SCHEMA PUBLIC FROM usr;

 GRANT EXECUTE ON FUNCTION consultacpf(cpf_input character varying) TO usr;

 GRANT SELECT ON TABLE examesolicitado TO usr;